# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Chaves da cozinha
email: chavesdacozinha@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Esse é o site para vocês acompanharem as receitas e atualizações nas 
  Chaves da Cozinha.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chavesdacozinha.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: maisonchaves
github_username:  chavescozinha

# Build settings
theme: jekyll-theme-so-simple
remote_theme: "mmistakes/so-simple-theme@3.2.0"
plugins:
  - jekyll-feed
disqus:
  shortname: chaves-da-cozinha

google_analytics: G-JKR60JQY6Q
search_full_content: true
collections:
  livros:
    output: true

locale: pt-BR
logo: images/icon.png
url: https://chavesdacozinha.github.io/

skin: "/assets/css/skins/default.css"
date_format: "%d/%m/%Y"

author:
  name: Maison Chaves
  twitter: maisonchaves
  picture: /images/eu.png

footer_links:
  - title: Twitter
    url: https://twitter.com/maisonchaves
    icon: fab fa-twitter-square
  - title: Youtube
    url: https://www.youtube.com/channel/UC6ncMjyehDmeDYiVMqryx5Q
    icon: fab fa-youtube-square
  - title: Feed
    url: feed.xml
    icon: fas fa-rss-square

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
# lsi: false
# safe: true
# source: [https://github.com/ChavesCozinha/chavescozinha.github.io]
# incremental: false
# highlighter: rouge
# gist:
#   noscript: false
# kramdown:
#   math_engine: mathjax
#   syntax_highlighter: rouge